FROM continuumio/miniconda3

SHELL ["/bin/bash", "-C"]
WORKDIR /code

# Install pre requisites
COPY ./environment.yml .
RUN conda env create -f environment.yml

# Add code
COPY ./metric-forecasting/metric_streaming.py .

CMD /opt/conda/envs/prophet-env/vin/python metric_streaming.py
