FROM python:3.8
WORKDIR /code

# Install pre requisites
COPY ./metric-forecasting/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Add code
COPY ./metric-forecasting/metric_streaming.py .

CMD [ "python", "./metric_streaming.py" ]
